// constants.dart

Map<String, String> stationIds = {
  "1": "Yio Chu Kang",
  "2": "Ang Mo Kio",
  "3": "Bishan NSEW",
  "4": "Braddell",
  "5": "Toa Payoh",
  "6": "Novena",
  "7": "Newton NSEW",
  "8": "Orchard NSEW",
  "9": "Somerset",
  "10": "Dhoby Ghaut NSEW",
  "11": "City Hall",
  "12": "Raffles Place",
  "13": "Marina Bay",
  "14": "Tanjong Pagar",
  "15": "Outram Park NSEW",
  "16": "Tiong Bahru",
  "17": "Redhill",
  "18": "Queenstown",
  "19": "Commonwealth",
  "20": "Buona Vista NSEW",
  "21": "Clementi",
  "22": "Yishun",
  "23": "Khatib",
  "24": "Jurong East",
  "25": "Chinese Garden",
  "26": "Lakeside",
  "27": "Boon Lay",
  "28": "Bukit Batok",
  "29": "Bukit Gombak",
  "30": "Choa Chu Kang",
  "31": "Bugis NSEW",
  "32": "Lavender",
  "33": "Kallang",
  "34": "Aljunied",
  "35": "Paya Lebar NSEW",
  "36": "Eunos",
  "37": "Kembangan",
  "38": "Bedok",
  "39": "Tanah Merah",
  "40": "Simei",
  "41": "Tampines NSEW",
  "42": "Pasir Ris",
  "43": "Sembawang",
  "44": "Admiralty",
  "45": "Woodlands (NSEW)",
  "46": "Marsiling",
  "47": "Kranji",
  "48": "Yew Tee",
  "49": "Choa Chu Kang BPLRT",
  "50": "South View",
  "51": "Keat Hong",
  "52": "Teck Whye",
  "53": "Phoenix",
  "54": "Bukit Panjang BPLRT",
  "55": "Petir",
  "56": "Pending",
  "57": "Bangkit",
  "58": "Fajar",
  "59": "Segar",
  "60": "Jelapang",
  "61": "Senja",
  "62": "Ten Mile Junction (Deprecated)",
  "63": "Expo NSEW",
  "64": "Dover",
  "65": "Changi Airport",
  "66": "Pioneer",
  "67": "Joo Koon",
  "68": "Marina South Pier",
  "69": "Gul Circle",
  "70": "Tuas Crescent",
  "71": "Tuas West Road",
  "72": "Tuas Link",
  "73": "Canberra",
  "88": "Test",
  "101": "Punggol",
  "102": "Sengkang",
  "103": "Buangkok",
  "104": "Hougang",
  "105": "Kovan",
  "106": "Serangoon NEL",
  "107": "Woodleigh",
  "108": "Potong Pasir"
};


Map<String, String> ticketTypes = {
  "1": "Adult",
  "2": "Child",
  "3": "Senior"
};

Map<String, String> journeyTypes = {
  "1": "One-Way",
  "2": "Return Trip"
};

Map<String, String> groupSizes = {
  "1": "Solo",
  "2": "Couple",
  "3": "Family",
  "4": "Group"
};